### ISSUE TITLE
[bug]click title will redirect to wrong issue page 

### ISSUE THREAD

**Issue by xiantang** [headllines/hackernews-daily#48]
I clicked 
![image](https://user-images.githubusercontent.com/34479567/92323388-e22cae00-f06a-11ea-9816-0cf6c4c510b3.png)
this title and it will redirect my browser to wrong page 
![image](https://user-images.githubusercontent.com/34479567/92323399-012b4000-f06b-11ea-9917-ed261736f6f1.png)
not hack news

**Comment by timqian** [comment]
Thanks for reporting. This is because the post does not have a corresponding URL. It is fixed now
